CREATE TABLE laps (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    race_id uuid REFERENCES races(id),
    driver_id uuid REFERENCES drivers(id),
    lap_number integer,
    lap_time interval,
    lap_improvement integer,
    crossing_finish_line_in_pit boolean,
    s1 interval,
    s1_improvement integer,
    s2 interval,
    s2_improvement integer,
    s3 interval,
    s3_improvement integer,
    kph float,
    elapsed interval,
    hour time,
    s1_large interval,
    s2_large interval,
    s3_large interval,
    top_speed float,
    pit_time interval,
    class text,
    "group" text,
    manufacturer text,
    flag_at_fl text,
    s1_seconds float,
    s2_seconds float,
    s3_seconds float,
    im1a_time interval,
    im1a_elapsed interval,
    im1_time interval,
    im1_elapsed interval,
    im2a_time interval,
    im2a_elapsed interval,
    im2_time interval,
    im2_elapsed interval,
    im3a_time interval,
    im3a_elapsed interval,
    fl_time interval,
    fl_elapsed interval,
    created_at timestamptz DEFAULT now()
);
